// convention for next.js. get the parameter using next.js's useRouter.

import { useRouter } from "next/router";
import CommentModal from "@/components/CommentModal";
import Sidebar from "@/components/Sidebar";
import Widget from "@/components/Widget";
import Head from "next/head";
import Post from "@/components/Post";
import { ArrowLeftIcon } from "@heroicons/react/outline";
import { useEffect, useState } from "react";
import { db } from "@/firebase";
import {
  collection,
  doc,
  onSnapshot,
  orderBy,
  query,
} from "firebase/firestore";
import { comment } from "postcss";
import Comment from "@/components/Comment";

export default function Postpage({ newsResults, randomUsersResults }) {
  const router = useRouter();
  const { id } = router.query; // getting the id from file name
  const [post, setPost] = useState(null);
  const [comments, setComments] = useState([]);

  useEffect(
    // get post data
    () => onSnapshot(doc(db, "posts", id), (snapshot) => setPost(snapshot)),
    [db, id]
  );

  useEffect(
    // get post comments
    () => {
      onSnapshot(
        query(
          collection(db, "posts", id, "comments"),
          orderBy("timestamp", "desc")
        ),
        (snapshot) => setComments(snapshot.docs)
      );
    },
    [db, id]
  );

  return (
    <div className="">
      <Head>
        <title>Post Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        {/* Sidebar */}
        <Sidebar />

        {/* Feed */}

        <div className="xl:ml-[370px] border-l border-r border-gray-200 sm:ml-[73px] flex-grow max-w-xl ">
          <div className="flex items-center space-x-2 py-2 px-3 sticky top-0 z-50 bg-white border-b border-gray-200">
            <div className="hoverEffect">
              <ArrowLeftIcon onClick={() => router.push("/")} className="h-5" />
            </div>
            <h2 className="text-lg sm:text-xl font-bold cursor-pointer">
              Tweet
            </h2>
          </div>

          <Post id={id} post={post} />
          {comments.length > 0 && (
            <div>
              {comments.map((comment) => (
                <Comment
                  key={comment.id}
                  id={comment.id}
                  comment={comment.data()}
                />
              ))}
            </div>
          )}
        </div>

        {/* Widgets */}
        <Widget
          newsResults={newsResults.articles}
          randomUsersResults={randomUsersResults.results}
        />

        {/* Modal */}
        <CommentModal />
      </main>
    </div>
  );
}

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export async function getServerSideProps() {
  // news
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((result) => result.json());

  // who to follow
  const randomUsersResults = await fetch(
    "https://randomuser.me/api/?results=30&inc=name,login,picture,email"
  ).then((result) => result.json());

  return { props: { newsResults, randomUsersResults } };
}
